export const STORE_ITEMS = [
  {
    id: "starter_tracksuit",
    category: "Tracksuits",
    name: "Starter Recovery Set",
    rarity: "Common",
    price: 0,
    currency: "coins",
    unlockLevel: 1,
    color: "#6B7280",
  },
  {
    id: "tokyo_tracksuit",
    category: "Tracksuits",
    name: "Tokyo Neon Runner",
    rarity: "Rare",
    price: 1500,
    currency: "coins",
    unlockLevel: 5,
    color: "#FF4D6D",
  },
  {
    id: "paris_tracksuit",
    category: "Tracksuits",
    name: "Paris Luxury Flow",
    rarity: "Epic",
    price: 3500,
    currency: "coins",
    unlockLevel: 15,
    color: "#06B6D4",
  },
  {
    id: "athens_tracksuit",
    category: "Tracksuits",
    name: "Athens Legacy Elite",
    rarity: "Legendary",
    price: 10000,
    currency: "coins",
    unlockLevel: 30,
    color: "#22C55E",
  },
  {
    id: "compression_shorts",
    category: "Shorts",
    name: "Compression Shorts",
    rarity: "Common",
    price: 400,
    currency: "coins",
    unlockLevel: 2,
    color: "#3B82F6",
  },
  {
    id: "elite_shorts",
    category: "Shorts",
    name: "Elite Marathon Shorts",
    rarity: "Rare",
    price: 1200,
    currency: "coins",
    unlockLevel: 8,
    color: "#F97316",
  },
  {
    id: "runner_shoes",
    category: "Shoes",
    name: "Legacy Runners",
    rarity: "Common",
    price: 800,
    currency: "coins",
    unlockLevel: 3,
    color: "#A6FFD2",
  },
  {
    id: "glow_shoes",
    category: "Shoes",
    name: "Glow Recovery Sneakers",
    rarity: "Epic",
    price: 5000,
    currency: "coins",
    unlockLevel: 20,
    color: "#8B5CF6",
  },
  {
    id: "calm_aura",
    category: "Auras",
    name: "Calm Recovery Aura",
    rarity: "Rare",
    price: 2500,
    currency: "wellness",
    unlockLevel: 10,
    color: "#A6FFD2",
  },
  {
    id: "legendary_aura",
    category: "Auras",
    name: "Legendary Gold Aura",
    rarity: "Legendary",
    price: 15000,
    currency: "wellness",
    unlockLevel: 40,
    color: "#FFD700",
  },
];